services:
  moodle:
    build: .
    ports:
      - "8080:80"
    volumes:
      - moodledata:/var/www/html/moodledata
    environment:
      - MOODLE_URL=http://localhost:8080
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle_password
      - MOODLE_DATABASE_HOST=db
    depends_on:
      - db
    command: bash -c "chown -R www-data:www-data /var/www && apache2-foreground"

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle_password

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - moodle

volumes:
  moodledata:
  dbdata: